-- Supabase SQL setup for Property Inventory System

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  asset_id text unique not null,
  education_level text,
  fund_cluster text,
  inventory_type text,
  property_no text,
  item_classification text,
  item_brand_model text,
  serial_no text,
  acquisition_date text,
  accountable_person text,
  school_level text,
  semi_expandable_no text,
  unit_value numeric check (unit_value is null or unit_value >= 0),
  total numeric check (total is null or total >= 0),
  unit_measurement text,
  balance numeric check (balance is null or balance >= 0),
  on_hand numeric check (on_hand is null or on_hand >= 0),
  shortage_overage_qty numeric,
  shortage_overage_value numeric,
  location text,
  mooe_month text,
  mooe_year numeric,
  date_issue text,
  status text,
  remarks text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.assets add column if not exists education_level text;

create table if not exists public.classifications (
  id bigint generated by default as identity primary key,
  classification_name text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  status_name text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.inventory_item (
  id bigint generated by default as identity primary key,
  inventory_item_type text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.geras_teacher (
  id bigint generated by default as identity primary key,
  teacher_name text not null,
  position text,
  school_level text,
  created_at timestamptz default now()
);

create table if not exists public.education_level (
  id bigint generated by default as identity primary key,
  education_level text unique not null,
  created_at timestamptz default now()
);

alter table public.inventory_item enable row level security;
alter table public.education_level enable row level security;

drop policy if exists "Allow public read access to inventory item types" on public.inventory_item;

create policy "Allow public read access to inventory item types" on public.inventory_item
  for select to anon, authenticated using (true);

drop policy if exists "Allow public read access to education levels" on public.education_level;

create policy "Allow public read access to education levels" on public.education_level
  for select to anon, authenticated using (true);

create unique index if not exists classifications_classification_name_key
  on public.classifications (classification_name);

create unique index if not exists statuses_status_name_key
  on public.statuses (status_name);

insert into public.statuses (status_name)
select distinct status
from public.assets
where status is not null and status <> ''
on conflict (status_name) do nothing;

alter table public.assets enable row level security;
alter table public.classifications enable row level security;
alter table public.statuses enable row level security;

drop policy if exists "Allow public read access to assets" on public.assets;
drop policy if exists "Allow public insert access to assets" on public.assets;
drop policy if exists "Allow public update access to assets" on public.assets;
drop policy if exists "Allow public delete access to assets" on public.assets;
drop policy if exists "Allow public read access to classifications" on public.classifications;
drop policy if exists "Allow public insert access to classifications" on public.classifications;
drop policy if exists "Allow public update access to classifications" on public.classifications;
drop policy if exists "Allow public delete access to classifications" on public.classifications;
drop policy if exists "Allow public read access to statuses" on public.statuses;
drop policy if exists "Allow public insert access to statuses" on public.statuses;
drop policy if exists "Allow public update access to statuses" on public.statuses;
drop policy if exists "Allow public delete access to statuses" on public.statuses;

create policy "Allow public read access to assets" on public.assets
  for select using (true);

create policy "Allow public insert access to assets" on public.assets
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to assets" on public.assets
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to assets" on public.assets
  for delete to anon, authenticated using (true);

create policy "Allow public read access to classifications" on public.classifications
  for select using (true);

create policy "Allow public insert access to classifications" on public.classifications
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to classifications" on public.classifications
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to classifications" on public.classifications
  for delete to anon, authenticated using (true);

create policy "Allow public read access to statuses" on public.statuses
  for select using (true);

create policy "Allow public insert access to statuses" on public.statuses
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to statuses" on public.statuses
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to statuses" on public.statuses
  for delete to anon, authenticated using (true);
