-- Supabase SQL setup for Property Inventory System

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  asset_id text unique not null,
  education_level text,
  fund_cluster text,
  inventory_type text,
  property_no text,
  item_classification text,
  item_brand_model text,
  serial_no text,
  acquisition_date text,
  accountable_person text,
  school_level text,
  semi_expandable_no text,
  unit_value numeric check (unit_value is null or unit_value >= 0),
  total numeric check (total is null or total >= 0),
  unit_measurement text,
  balance numeric check (balance is null or balance >= 0),
  on_hand numeric check (on_hand is null or on_hand >= 0),
  shortage_overage_qty numeric,
  shortage_overage_value numeric,
  location text,
  mooe_month text,
  mooe_year numeric,
  date_issue text,
  status text,
  remarks text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.assets add column if not exists education_level text;
alter table public.assets add column if not exists additional_item text;

create table if not exists public.classifications (
  id bigint generated by default as identity primary key,
  classification_name text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  status_name text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.inventory_item (
  id bigint generated by default as identity primary key,
  inventory_item_type text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.school_teacher (
  id                  bigint generated by default as identity primary key,
  -- Basic identity
  teacher_name        text not null,
  employee_id         text unique,
  -- Position / assignment
  position            text,
  plantilla_position  text,
  school_level        text,
  personnel_type      text,           -- e.g. "Teaching Personnel", "Non-Teaching"
  grade_section       text,           -- e.g. "Grade 6 – Adviser"
  -- Contact
  email               text,
  phone               text,
  -- School & location
  school_name         text,
  location            text,           -- e.g. classroom or office location
  -- Employment details
  date_hired          date,
  employment_status   text,           -- e.g. "Permanent", "Contractual"
  status              text default 'Active',  -- record status: Active / Inactive
  -- Photo
  photo_url           text,
  -- Audit
  created_at          timestamptz default now()
);

-- Migration helper: add new columns to existing school_teacher table
-- (safe to run on a database that already has the table)
alter table if exists public.school_teacher add column if not exists employee_id        text unique;
alter table if exists public.school_teacher add column if not exists plantilla_position text;
alter table if exists public.school_teacher add column if not exists personnel_type     text;
alter table if exists public.school_teacher add column if not exists grade_section      text;
alter table if exists public.school_teacher add column if not exists email              text;
alter table if exists public.school_teacher add column if not exists phone              text;
alter table if exists public.school_teacher add column if not exists school_name        text;
alter table if exists public.school_teacher add column if not exists location           text;
alter table if exists public.school_teacher add column if not exists date_hired         date;
alter table if exists public.school_teacher add column if not exists employment_status  text;
alter table if exists public.school_teacher add column if not exists status             text default 'Active';
alter table if exists public.school_teacher add column if not exists photo_url          text;


create table if not exists public.education_level (
  id bigint generated by default as identity primary key,
  education_level text unique not null,
  created_at timestamptz default now()
);

create table if not exists public.signatories (
  id bigint generated by default as identity primary key,
  signatory text unique not null,
  created_at timestamptz default now()
);

alter table public.inventory_item enable row level security;
alter table public.education_level enable row level security;
alter table public.signatories enable row level security;
alter table public.school_teacher enable row level security;

drop policy if exists "Allow public read and write access to school_teacher" on public.school_teacher;

create policy "Allow public read and write access to school_teacher" on public.school_teacher
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "Allow public read access to inventory item types" on public.inventory_item;

create policy "Allow public read access to inventory item types" on public.inventory_item
  for select to anon, authenticated using (true);

drop policy if exists "Allow public read access to education levels" on public.education_level;

create policy "Allow public read access to education levels" on public.education_level
  for select to anon, authenticated using (true);

drop policy if exists "Allow public read access to signatories" on public.signatories;

create policy "Allow public read access to signatories" on public.signatories
  for select to anon, authenticated using (true);

create unique index if not exists classifications_classification_name_key
  on public.classifications (classification_name);

create unique index if not exists statuses_status_name_key
  on public.statuses (status_name);

insert into public.statuses (status_name)
select distinct status
from public.assets
where status is not null and status <> ''
on conflict (status_name) do nothing;

alter table public.assets enable row level security;
alter table public.classifications enable row level security;
alter table public.statuses enable row level security;

drop policy if exists "Allow public read access to assets" on public.assets;
drop policy if exists "Allow public insert access to assets" on public.assets;
drop policy if exists "Allow public update access to assets" on public.assets;
drop policy if exists "Allow public delete access to assets" on public.assets;
drop policy if exists "Allow public read access to classifications" on public.classifications;
drop policy if exists "Allow public insert access to classifications" on public.classifications;
drop policy if exists "Allow public update access to classifications" on public.classifications;
drop policy if exists "Allow public delete access to classifications" on public.classifications;
drop policy if exists "Allow public read access to statuses" on public.statuses;
drop policy if exists "Allow public insert access to statuses" on public.statuses;
drop policy if exists "Allow public update access to statuses" on public.statuses;
drop policy if exists "Allow public delete access to statuses" on public.statuses;

create policy "Allow public read access to assets" on public.assets
  for select using (true);

create policy "Allow public insert access to assets" on public.assets
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to assets" on public.assets
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to assets" on public.assets
  for delete to anon, authenticated using (true);

create policy "Allow public read access to classifications" on public.classifications
  for select using (true);

create policy "Allow public insert access to classifications" on public.classifications
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to classifications" on public.classifications
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to classifications" on public.classifications
  for delete to anon, authenticated using (true);

create policy "Allow public read access to statuses" on public.statuses
  for select using (true);

create policy "Allow public insert access to statuses" on public.statuses
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to statuses" on public.statuses
  for update to anon, authenticated using (true) with check (true);

create policy "Allow public delete access to statuses" on public.statuses
  for delete to anon, authenticated using (true);

-- Inventory Custodian Slip (ICS) document records.
-- Keep these separate from assets: a slip is a historical custody document and can contain multiple assets.
create table if not exists public.ics_slips (
  id bigint generated by default as identity primary key,
  ics_no text not null unique,
  entity_name text not null,
  fund_cluster text,
  received_from_name text,
  received_from_position text,
  received_from_date date,
  received_by_name text,
  received_by_position text,
  received_by_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ics_slip_items (
  id bigint generated by default as identity primary key,
  ics_slip_id bigint not null references public.ics_slips(id) on delete cascade,
  line_no integer not null check (line_no > 0),
  asset_id bigint references public.assets(id) on delete set null,
  inventory_item_no text,
  description_snapshot text not null,
  quantity numeric(14, 2) not null check (quantity > 0),
  unit text,
  unit_cost numeric(14, 2) not null check (unit_cost >= 0),
  total_cost numeric(14, 2) not null check (total_cost >= 0),
  estimated_useful_life text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (ics_slip_id, line_no)
);

create index if not exists ics_slip_items_ics_slip_id_idx
  on public.ics_slip_items (ics_slip_id);

create index if not exists ics_slip_items_asset_id_idx
  on public.ics_slip_items (asset_id);

create or replace function public.set_ics_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_ics_slips_updated_at on public.ics_slips;
create trigger set_ics_slips_updated_at
  before update on public.ics_slips
  for each row execute function public.set_ics_updated_at();

drop trigger if exists set_ics_slip_items_updated_at on public.ics_slip_items;
create trigger set_ics_slip_items_updated_at
  before update on public.ics_slip_items
  for each row execute function public.set_ics_updated_at();

-- Security baseline: no anonymous access. Add authenticated role/owner policies
-- before connecting the browser CRUD UI to these tables.
alter table public.ics_slips enable row level security;
alter table public.ics_slip_items enable row level security;
-- Temporary no-login app policies. Replace with authenticated, role-based policies before production use.
drop policy if exists "Allow public ICS slip access" on public.ics_slips;
drop policy if exists "Allow public ICS slip item access" on public.ics_slip_items;

create policy "Allow public ICS slip access" on public.ics_slips
  for all to anon, authenticated using (true) with check (true);

create policy "Allow public ICS slip item access" on public.ics_slip_items
  for all to anon, authenticated using (true) with check (true);

-- Report of Semi-Expendable Property Issued (RSPI) document records.
-- A report header stores the input/base record. Its line items are snapshots of
-- the source ICS items so an issued RSPI remains reproducible after ICS changes.
create table if not exists public.rspi_reports (
  id bigint generated by default as identity primary key,
  serial_no text not null unique,
  entity_name text not null,
  fund_cluster text,
  report_date date not null,
  responsibility_center_code text,
  source_ics_slip_id bigint references public.ics_slips(id) on delete set null,
  source_ics_no text,
  custodian_name text,
  accounting_staff_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rspi_report_items (
  id bigint generated by default as identity primary key,
  rspi_report_id bigint not null references public.rspi_reports(id) on delete cascade,
  line_no integer not null check (line_no > 0),
  source_ics_slip_id bigint references public.ics_slips(id) on delete set null,
  source_ics_slip_item_id bigint references public.ics_slip_items(id) on delete set null,
  ics_no_snapshot text not null,
  responsibility_center_code text,
  semi_expendable_property_no text,
  description_snapshot text not null,
  unit text,
  quantity_issued numeric(14, 2) not null check (quantity_issued > 0),
  unit_cost numeric(14, 2) not null check (unit_cost >= 0),
  amount numeric(14, 2) not null check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rspi_report_id, line_no)
);

create index if not exists rspi_report_items_rspi_report_id_idx
  on public.rspi_report_items (rspi_report_id);

create index if not exists rspi_report_items_source_ics_slip_id_idx
  on public.rspi_report_items (source_ics_slip_id);

drop trigger if exists set_rspi_reports_updated_at on public.rspi_reports;
create trigger set_rspi_reports_updated_at
  before update on public.rspi_reports
  for each row execute function public.set_ics_updated_at();

drop trigger if exists set_rspi_report_items_updated_at on public.rspi_report_items;
create trigger set_rspi_report_items_updated_at
  before update on public.rspi_report_items
  for each row execute function public.set_ics_updated_at();

alter table public.rspi_reports enable row level security;
alter table public.rspi_report_items enable row level security;
drop policy if exists "Allow public RSPI report access" on public.rspi_reports;
drop policy if exists "Allow public RSPI report item access" on public.rspi_report_items;

create policy "Allow public RSPI report access" on public.rspi_reports
  for all to anon, authenticated using (true) with check (true);

create policy "Allow public RSPI report item access" on public.rspi_report_items
  for all to anon, authenticated using (true) with check (true);

-- ============================================================================
-- PRODUCTION HARDENING
-- ----------------------------------------------------------------------------
-- The policies above are intentionally permissive so the no-login app works out
-- of the box. Before deploying to a real environment, run the statements below
-- to switch to the recommended security baseline:
--
--   * Public (anon) can only READ asset/lookup data (needed for the QR asset
--     detail page and public dashboard).
--   * All INSERT / UPDATE / DELETE operations require a signed-in user
--     (the `authenticated` role).
--
-- You must also enable Supabase Auth (e.g. email/password) and have the app
-- attach the user's access token to the Authorization header on mutations.
-- ============================================================================

-- assets: keep public read, restrict mutations to authenticated
drop policy if exists "Allow public insert access to assets" on public.assets;
drop policy if exists "Allow public update access to assets" on public.assets;
drop policy if exists "Allow public delete access to assets" on public.assets;

create policy "Allow authenticated insert access to assets" on public.assets
  for insert to authenticated with check (true);

create policy "Allow authenticated update access to assets" on public.assets
  for update to authenticated using (true) with check (true);

create policy "Allow authenticated delete access to assets" on public.assets
  for delete to authenticated using (true);

-- classifications: keep public read, restrict mutations to authenticated
drop policy if exists "Allow public insert access to classifications" on public.classifications;
drop policy if exists "Allow public update access to classifications" on public.classifications;
drop policy if exists "Allow public delete access to classifications" on public.classifications;

create policy "Allow authenticated insert access to classifications" on public.classifications
  for insert to authenticated with check (true);

create policy "Allow authenticated update access to classifications" on public.classifications
  for update to authenticated using (true) with check (true);

create policy "Allow authenticated delete access to classifications" on public.classifications
  for delete to authenticated using (true);

-- statuses: keep public read, restrict mutations to authenticated
drop policy if exists "Allow public insert access to statuses" on public.statuses;
drop policy if exists "Allow public update access to statuses" on public.statuses;
drop policy if exists "Allow public delete access to statuses" on public.statuses;

create policy "Allow authenticated insert access to statuses" on public.statuses
  for insert to authenticated with check (true);

create policy "Allow authenticated update access to statuses" on public.statuses
  for update to authenticated using (true) with check (true);

create policy "Allow authenticated delete access to statuses" on public.statuses
  for delete to authenticated using (true);

-- ICS: keep public read, restrict mutations to authenticated
drop policy if exists "Allow public ICS slip access" on public.ics_slips;
drop policy if exists "Allow public ICS slip item access" on public.ics_slip_items;

create policy "Allow authenticated ICS slip access" on public.ics_slips
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated ICS slip item access" on public.ics_slip_items
  for all to authenticated using (true) with check (true);

-- RSPI: keep public read, restrict mutations to authenticated
drop policy if exists "Allow public RSPI report access" on public.rspi_reports;
drop policy if exists "Allow public RSPI report item access" on public.rspi_report_items;

create policy "Allow authenticated RSPI report access" on public.rspi_reports
  for all to authenticated using (true) with check (true);

create policy "Allow authenticated RSPI report item access" on public.rspi_report_items
  for all to authenticated using (true) with check (true);

-- school_details table
create table if not exists public.school_details (
  id bigint generated by default as identity primary key,
304 |   school_name text not null,
305 |   school_id bigint,
306 |   school_logo_url text,
307 |   created_at timestamptz default now()
);

alter table public.school_details enable row level security;

drop policy if exists "Allow public read access to school details" on public.school_details;
drop policy if exists "Allow public insert access to school details" on public.school_details;
drop policy if exists "Allow public update access to school details" on public.school_details;

create policy "Allow public read access to school details" on public.school_details
  for select using (true);

create policy "Allow public insert access to school details" on public.school_details
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to school details" on public.school_details
  for update to anon, authenticated using (true) with check (true);

-- qr_download_history table
create table if not exists public.qr_download_history (
  id bigint generated by default as identity primary key,
  asset_id text not null unique,
  property_no text,
  item_brand_model text,
  download_count integer default 1 check (download_count > 0),
  downloaded_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.qr_download_history enable row level security;

drop policy if exists "Allow public read access to qr_download_history" on public.qr_download_history;
drop policy if exists "Allow public insert access to qr_download_history" on public.qr_download_history;
drop policy if exists "Allow public update access to qr_download_history" on public.qr_download_history;

create policy "Allow public read access to qr_download_history" on public.qr_download_history
  for select using (true);

create policy "Allow public insert access to qr_download_history" on public.qr_download_history
  for insert to anon, authenticated with check (true);

create policy "Allow public update access to qr_download_history" on public.qr_download_history
  for update to anon, authenticated using (true) with check (true);

-- =====================================================
-- STORAGE SETUP: Personnel Profile Photos
-- =====================================================
-- Create 'personnel-photos' storage bucket for profile avatars
insert into storage.buckets (id, name, public)
values ('personnel-photos', 'personnel-photos', true)
on conflict (id) do update set public = true;

-- Public read access to personnel-photos
drop policy if exists "Public Access personnel-photos" on storage.objects;
create policy "Public Access personnel-photos"
on storage.objects for select
using ( bucket_id = 'personnel-photos' );

-- Public/anon upload access to personnel-photos
drop policy if exists "Allow Public Upload personnel-photos" on storage.objects;
create policy "Allow Public Upload personnel-photos"
on storage.objects for insert
to anon, authenticated
with check ( bucket_id = 'personnel-photos' );

-- Public/anon update access to personnel-photos
drop policy if exists "Allow Public Update personnel-photos" on storage.objects;
create policy "Allow Public Update personnel-photos"
on storage.objects for update
to anon, authenticated
using ( bucket_id = 'personnel-photos' );

